const Localization = {
    messages: {
        en: {
            title: 'Five Tribes: The Djinns Of Naqala',
            subtitle: 'Board Game Score Calculator',
            sourceCode: 'Source Code',
            player: {
                1: 'Player One',
                2: 'Player Two',
                3: 'Player Three',
                4: 'Player Four',
            },
            setPlayerResults: 'Set Player Results',
            goldCoinsScore: 'Gold Coins Score',
            goldCoinsAmount: 'Gold Coins Amount',
            viziersScore: 'Viziers Score',
            yellowMeeplesNumber: 'Number of yellow meeples',
            eldersScore: 'Elders Score',
            whiteMeeplesNumber:'Number of white meeples',
            djinniesScore:'Djinns Score',
            selectDjinnies:'Select Djinns',
            djinnName: {
                AlAmin:'Al-Amin ({1} VPs)',
                AnunNak:'Anun-Nak ({1} VPs)',
                Baal: "Ba'al ({1} VPs)",
                Boaz: 'Boaz ({1} VPs)',
                Boaraq: 'Boaraq ({1} VPs)',
                Echidna: 'Echidna ({1} VPs)',
                Enki: 'Enki ({1} VPs)',
                Hagis: 'Hagis ({1} VPs)',
                Haurvatat: 'Haurvatat ({1} VPs) [Each Palm Tree is worth 5 VPs instead of 3]',
                Iblis: 'Iblis ({1} VPs)',
                Jafaar: 'Jafaar ({1} VPs) [Each Vizier is worth 3 VPs instead of 1]',
                Kandicha: 'Kandicha ({1} VPs)',
                Kumarbi: 'Kumarbi ({1} VPs)',
                Lamia: 'Lamia ({1} VPs)',
                Leta: 'Leta ({1} VPs)',
                Marid: 'Marid ({1} VPs)',
                Monkir: 'Monkir ({1} VPs)',
                Nekir: 'Nekir ({1} VPs)',
                Shamhat: 'Shamhat ({1} VPs) [Each Elder is worth 4 VPs instead of 2]',
                Sibitis: 'Sibitis ({1} VPs)',
                Sloar: 'Sloar ({1} VPs)',
                Utug: 'Utug ({1} VPs)'
            },
            palmTreesScore: 'Palm Trees Score',
            palmTreesNumber: 'Number of palm trees',
            palacesScore: 'Palaces Score',
            palacesCount: 'Number of palaces',
            playerTilesScore: 'Player Tiles Score',
            selectPlayerTiles: 'Select Player Tiles',
            addVPsTile: 'Add {1} VPs tile',
            merchandiseScore: 'Merchandise Score',
            selectMerchandiseCardSuits: 'Select Merchandise Card Suits',
            addMerchandiseCardSuit: 'Add {1} card suit',
            merchandiseCardSuit: '{1} card suit - {2} VPs',
            addPlayer: 'Add player',
            totalScore: 'Total Score'
        },
        ru: {
            title: 'Пять племён: Джинны Накалы',
            subtitle: 'Счётчик очков настольной игры',
            sourceCode: 'Исходный код',
            player: {
                1: 'Первый игрок',
                2: 'Второй игрок',
                3: 'Третий игрок',
                4: 'Четвёртый игрок',
            },
            setPlayerResults: 'Заполнить результаты',
            goldCoinsScore: 'ПО за золотые монеты',
            goldCoinsAmount: 'Количество золотых монет',
            viziersScore: 'ПО за визирей',
            yellowMeeplesNumber: 'Количество жёлтых миплов',
            eldersScore: 'ПО за старейшин',
            whiteMeeplesNumber:'Количество белых миплов',
            djinniesScore:'ПО за джиннов',
            selectDjinnies:'Выберите джиннов',
            djinnName: {
                AlAmin: 'Аль-Амин ({1} ПО)',
                AnunNak: 'Ануннак ({1} ПО)',
                Baal: 'Баал ({1} ПО)',
                Boaz: 'Вооз ({1} ПО)',
                Boaraq: 'Бурак ({1} ПО)',
                Echidna: 'Ехидна ({1} ПО)',
                Enki: 'Эа ({1} ПО)',
                Hagis: 'Хегис ({1} ПО)',
                Haurvatat: 'Аурват ({1} ПО) [Каждая пальма приносит 5 ПО вместо 3]',
                Iblis: 'Иблис ({1} ПО)',
                Jafaar: 'Джафар ({1} ПО) [Каждый визирь приносит 3 ПО вместо 1]',
                Kandicha: 'Кандиша ({1} ПО)',
                Kumarbi: 'Кумарби ({1} ПО)',
                Lamia: 'Ламия ({1} ПО)',
                Leta: 'Лета ({1} ПО)',
                Marid: 'Марид ({1} ПО)',
                Monkir: 'Мункар ({1} ПО)',
                Nekir: 'Накир ({1} ПО)',
                Shamhat: 'Шамхат ({1} ПО) [Каждый старейшина приносит 4 ПО вместо 2]',
                Sibitis: 'Себитти ({1} ПО)',
                Sloar: 'Слор ({1} ПО)',
                Utug: 'Утуг ({1} ПО)'
            },
            palmTreesScore: 'ПО за пальмы',
            palmTreesNumber: 'Количество пальм',
            palacesScore: 'ПО за дворцы',
            palacesCount: 'Количество дворцов',
            playerTilesScore: 'ПО за султанаты игрока',
            selectPlayerTiles: 'Выберите султанаты игрока',
            addVPsTile: 'Султанат за {1} ПО',
            merchandiseScore: 'ПО за товары',
            selectMerchandiseCardSuits: 'Выберите сеты карт товаров',
            addMerchandiseCardSuit: 'Сет из {1} товаров',
            merchandiseCardSuit: 'Сет из {1} товаров - {2} ПО',
            addPlayer: 'Добавить игрока',
            totalScore: 'Итоговый счёт'
        },
        de: {
            title: 'Five Tribes: die Dschinn von Naqala',
            subtitle: 'Der Brettspiel-Punktzahl-Rechner',
            sourceCode: 'Der Quellcode',
            player: {
                1: 'Der erste Spieler',
                2: 'Der zweite Spieler',
                3: 'Der dritte Spieler',
                4: 'Der vierte Spieler',
            },
            setPlayerResults: 'Spielergebnis festlegen',
            goldCoinsScore: 'Die Bewertung von Goldmünzen',
            goldCoinsAmount: 'Der Goldmünzenbetrag',
            viziersScore: 'Die Bewertung von die Wesire',
            yellowMeeplesNumber: 'Die Bewertung von gelbe Meeples',
            eldersScore: 'Die Bewertung von die Ältesten',
            whiteMeeplesNumber:'Die Bewertung von weiße Meeples',
            djinniesScore:'Die Bewertung von die Dschinnen',
            selectDjinnies:'Wählen Sie die Dschinnen',
            djinnName: {
                AlAmin:'Al-Amin ({1} SP)',
                AnunNak:'Anun-Nak ({1} SP)',
                Baal: "Ba'al ({1} SP)",
                Boaz: 'Boaz ({1} SP)',
                Boaraq: 'Boaraq ({1} SP)',
                Echidna: 'Echidna ({1} SP)',
                Enki: 'Enki ({1} SP)',
                Hagis: 'Hagis ({1} SP)',
                Haurvatat: 'Haurvatat ({1} SP) [Erhälst du für jede deiner Palmen 5 SP (anstatt 3 SP)]',
                Iblis: 'Iblis ({1} SP)',
                Jafaar: 'Jafaar ({1} SP) [Erhälst du für jeden deiner Wesire 3 SP (anstatt 1 SP)]',
                Kandicha: 'Kandicha ({1} SP)',
                Kumarbi: 'Kumarbi ({1} SP)',
                Lamia: 'Lamia ({1} SP)',
                Leta: 'Leta ({1} SP)',
                Marid: 'Marid ({1} SP)',
                Monkir: 'Monkir ({1} SP)',
                Nekir: 'Nekir ({1} SP)',
                Shamhat: 'Shamhat ({1} SP) [Erhälst du für jeden deiner Ältesten 4 SP (anstatt 2 SP)]',
                Sibitis: 'Sibitis ({1} SP)',
                Sloar: 'Sloar ({1} SP)',
                Utug: 'Utug ({1} SP)'
            },
            palmTreesScore: 'Die Bewertung von Palmen',
            palmTreesNumber: 'Der Palmenbetrag',
            palacesScore: 'Die Bewertung von Dorfen',
            palacesCount: 'Der Dorfenbetrag',
            playerTilesScore: 'Die Bewertung von Spielerplättchen',
            selectPlayerTiles: 'Wählen Sie die Spielerplättchen',
            addVPsTile: 'Hinzufügen {1} SP Plättchen',
            merchandiseScore: 'Die Bewertung von Güter',
            selectMerchandiseCardSuits: 'Wählen Sie die Güterkartenset',
            addMerchandiseCardSuit: 'Hinzufügen {1} Karteneinheiten',
            merchandiseCardSuit: '{1} Karteneinheit - {2} SP',
            addPlayer: 'Hinzufügen den Spieler',
            totalScore: 'Das Gesamtergebnis'
        }
    },
    getLocaleMessages(locale) {
        return this.messages[locale];
    }
}

