const Settings = {
    DEFAULT_PALM_TREE_VICTORY_POINTS: 3,
    DJINN_HAURVATAT_PALM_TREE_VICTORY_POINTS: 5,
    DEFAULT_VIZIER_VICTORY_POINTS: 1,
    DJINN_JAFAAR_VIZIER_VICTORY_POINTS: 3,
    DEFAULT_ELDER_VICTORY_POINTS: 2,
    DJINN_SHAMHAT_ELDER_VICTORY_POINTS: 4,
    DEFAULT_PALACE_VICTORY_POINTS: 5
}